### ISSUE TITLE
support vmnet settings other than the default ones

### ISSUE THREAD

**Issue by fakiolinho** [AntonioMeireles/coreos-xhyve#56] opened 2016-01-25 11:45 UTC
A very strange error appears after running `sudo corectl run` using corectl 0.5.3 on Mac OSX 10.11.2. This is the output:

``` bash
...
This is localhost (Linux x86_64 4.4.0-coreos-r2) 11:32:06
SSH host key: SHA256:CtOex5Ol+AoQW3JQAmoAueQJQPME2MQqmknBGEbtQfg (DSA)
SSH host key: SHA256:HHzHzxnTZ//sUQbSeM7+ZTkYaOkz3arYCWimOqv8hoQ (ED25519)
SSH host key: SHA256:UfHgkksViAtpnGSFWuRmrlRpExl+MPCrJ687w90hZe4 (RSA)
eth0: 192.168.65.10 fe80::40a4:aff:fe6b:cf32

localhost login: core (automatic login)

CoreOS stable (935.0.0)
Last login: Mon Jan 25 11:32:06 +0000 2016 on /dev/tty1.
Update Strategy: No Reboots
core@localhost ~ $ Error: Unable to grab VM's IP after 30s (!)... Aborting

                                                                          Usage: 
                                                                                   corectl run [flags]

                                                                                                      Aliases:
                                                                                                                run, start

                                                                                                                          Flags:
                                                                                                                                      --cdrom string          append an CDROM (.iso) to VM
                                  --channel string        CoreOS channel (default "alpha")
                                                                                                --cloud_config string   cloud-config file location (either a remote URL or a local path)
                                --cpus int              VM's vCPUS (default 1)
                                                                                -d, --detached              starts the VM in detached (background) mode
                                                                                                                                                         -h, --help                  help for run
                                     -l, --local latest          consumes whatever image is latest locally instead of looking online unless there's nothing available.
              --memory int            VM's RAM, in MB, per instance (1024 < memory < 8192) (default 1024)
                                                                                                           -n, --name string           names the VM. (if absent defaults to VM's UUID)
                              --root string           append a (persistent) root volume to VM
                                                                                                   --sshkey string         VM's default ssh key
                                                                                                                                                     --tap string            append tap interface to VM
                                               --uuid string           VM's UUID (default "random")
                                                                                                         --version string        marios:mist.core marios$
```

**Comment by AntonioMeireles** [comment] 2016-01-25 11:49
@fakiolinho hi, thanks for reporting!.
some quick questions for context: 
- what arguments are you passing to `corectl` (full command line, please) ?
- Is this reproduceable ?
- `ps -ax | grep corectl`  gives you what ?
- what OS X version are you running ?

**Comment by fakiolinho** [comment] 2016-01-25 11:59
No problem @AntonioMeireles so:
- `sudo corectl run`
- Yes i ve just reproduced it
- `10793 ttys001    0:00.00 grep corectl`
- OSX El Capitan 10.11.2

**Comment by AntonioMeireles** [comment] 2016-01-25 12:00
@fakiolinho 
i just spoted what the problem is ... 
your VM is getting an IP in the `192.168.65.0/24` range and not in the (default) `192.168.64.0/24` one. this is not a supported configuration yet. any special reason for you being unable to use OS defaults ?

**Comment by AntonioMeireles** [comment] 2016-01-25 21:38
@fakiolinho 

If i got it right, test patch consumed bellow should get this fixed. so, could you please try this steps, 
on a `corectl` checkout, and confirm it ? :smile:

```
curl -Ls https://gist.github.com/AntonioMeireles/741f706a1ca75b1582a2/raw/177f29ab3c69abc71e2f6f1a8d3c44c33af6cb6e/- | patch -p0
make
./corectl pull -f
```

and then try to use `corectl` normally... Thanks again for your patience!

**Comment by AntonioMeireles** [comment] 2016-01-25 21:57
@rimusz try this please too. fwiw for the common case _fix_ shouldn't break anything
 (just don't jump over plz the `./corectl pull -f` step as images have to be regenerated _atm_)

**Comment by AntonioMeireles** [comment] 2016-01-28 09:35
@fakiolinho i just merged #58  which afaict should fix this (@rimusz acked it ouf of band) out of the box (will be consumed in next release, and in homebrew later today). If for some reason your issue persists in some way please reopen. Thanks for reporting!

**Comment by d-mo** [comment] 2016-02-07 22:53
I hit the above error as well and I can confirm that after upgrading to corectl 0.5.4 the VM starts fine with an ip address in the 192.168.65.0/24 range. However, my home folder will not get mounted over NFS. 

I think the reason for this is the /etc/systemd/system/Users-dimo.mount unit file, which tries to mount 192.168.64.1:/Users/dimo instead of 192.168.65.1:/Users/dimo

**Comment by AntonioMeireles** [comment] 2016-02-08 08:34
@d-mo, 

that's... strange. :disappointed: 

a) what exact `corectl` version are you running?
b) paste contexts of your `etc/exports`
c) can you run a `correct pull -wf` (to force a rebuild of the local images) and try again ?

and thanks for your patience!

**Comment by d-mo** [comment] 2016-02-08 19:40
I'm running 0.5.4
`correct pull -wf` fixed it! Thanks!

**Comment by AntonioMeireles** [comment] 2016-06-04 14:49
afaict current versions handle custom vmnet settings transparently. if there's still side effects bug us again :-)

**Closed as completed by AntonioMeireles** 2016-06-04 14:49 UTC
Labels: bug, enhancement
